<?php

return [
    'phone_type' => env('DV_phone_type', null),
    'record_type' => env('DV_record_type', null),
    'record_status' => env('DV_record_status', null),
    'call_result' => env('DV_call_result', null),
    'attempt' => env('DV_attempt', null),
    'dial_sched_time' => env('DV_dial_sched_time', null),
    'call_time' => env('DV_call_time', null),
    'daily_from' => env('DV_daily_from', null),
    'daily_till' => env('DV_daily_till', null),
    'tz_dbid' => env('DV_tz_dbid', null),
    'campaign_id' => env('DV_campaign_id', null),
    'agent_id' => env('DV_agent_id', null),
    'chain_id' => env('DV_chain_id', null),
    'chain_n' => env('DV_chain_n', null),
    'app_id' => env('DV_app_id', null),
    'treatments' => env('DV_treatments', null),
    'contact_info' => env('DV_contact_info', null),
    'contact_info_type' => env('DV_contact_info_type', null),
    'switch_id' => env('DV_switch_id', null),
    'Cancel_Reason' => env('DV_Cancel_Reason', null),
    'Customer_Name' => env('DV_Customer_Name', null),
    'Dzherelo' => env('DV_Dzherelo', null),
    'Out_Date' => env('DV_Out_Date', null),
    'Region' => env('DV_Region', null),
    'HotOutStatus' => env('DV_HotOutStatus', null),
];